#!/usr/bin/env bash

# build config file
php /boot.d/nextcloud/nc_config.php "${NC_BASE_PATH}/config/config.php"

# run official entrypoint – it needs at least a parameter 1 ...
/entrypoint.sh apache-nextcloud-entrypoint-done

# run bootup scripts
/boot.sh

# if given CMD is `start` do NextCloud startup
if [ "$1" == "start" ]; then
    {{ STARTUP_COMMAND }}
else
    exec "$@"
fi
