#!/usr/bin/env bash

# run official entrypoint – it needs at least a parameter 1 ...
/entrypoint.sh apache-nextcloud-entrypoint-done

# run bootup scripts
/boot.sh

# if given CMD is `start` do NextCloud startup
if [ "$1" == "start" ]; then
    {{ STARTUP_COMMAND }}
else
    exec "$@"
fi
